import { Recommendation, Status } from './types';

export const RECOMMENDATIONS: Recommendation[] = [
  {
    id: "R01",
    chapter: "1. Compute & Infrastructure",
    title: "Set out, within 6 months, a long-term plan for UK's AI infrastructure needs, backed by a 10-year inv...",
    description: "Set out, within 6 months, a long-term plan for UK's AI infrastructure needs, backed by a 10-year investment commitment.",
    department: "DSIT",
    status: Status.COMPLETED,
    deliveryTimeline: "Spring 2025",
    govResponse: "Agree. DSIT will publish a long-term compute strategy in Spring 2025 and is committed to setting out a 10-year roadmap for compute.",
    progress: "The UK Compute Roadmap (CP 1352) was published on 21 July 2025, providing a 10-year investment horizon and committing up to £2 billion to build a modern public compute ecosystem. The roadmap details the transition from current capabilities to a 2030 target.",
    lastUpdate: "July"
  },
  {
    id: "R02",
    chapter: "1. Compute & Infrastructure",
    title: "Expand the capacity of AIRR by at least 20x by 2030 – starting within 6 months.",
    description: "Expand the capacity of AIRR by at least 20x by 2030 – starting within 6 months.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "2024/2025 FY to 2030/2031 FY",
    govResponse: "Agree. DSIT will set out how we will deliver on this as part of its long-term compute strategy. We are making a start next year by starting delivery of a new state of the art supercomputing facility that will at least double the capacity of our national AI Research Resource.",
    progress: "Isambard-AI went live in July 2025. AIRR guidance and access routes were published. The Compute Roadmap reiterated commitment to expand AIRR 20x by 2030.",
    lastUpdate: "July"
  },
  {
    id: "R03",
    chapter: "1. Compute & Infrastructure",
    title: "Strategically allocate sovereign compute by appointing mission-focused 'AIRR programme directors' wi...",
    description: "Strategically allocate sovereign compute by appointing mission-focused 'AIRR programme directors' with significant autonomy.",
    department: "DSIT",
    status: Status.PARTIALLY,
    deliveryTimeline: "Spring 2025",
    govResponse: "Agree. DSIT will set out mission-focused plans for allocation of compute as part of a long-term compute strategy that will be published in Spring 2025.",
    progress: "No public announcement of named programme directors. The Compute Roadmap introduced a refreshed allocation model, dedicated tracks for the Sovereign AI Unit and AISI, and an AIRRPORT 'single front door', but no named director appointments published. Sovereign AI AIRR had a call for researchers in the summer.",
    lastUpdate: "July"
  },
  {
    id: "R04",
    chapter: "1. Compute & Infrastructure",
    title: "Establish 'AI Growth Zones' (AIGZ) to facilitate the accelerated build out of AI data centres.",
    description: "Establish 'AI Growth Zones' (AIGZ) to facilitate the accelerated build out of AI data centres.",
    department: "DSIT",
    status: Status.COMPLETED,
    deliveryTimeline: "Spring 2025",
    govResponse: "Agree. The government will deliver the first AI Growth Zone at Culham, the headquarters of the UK Atomic Energy Authority (UKAEA), subject to the agreement of a public-private partnership that delivers benefits to the local area, the UKAEA's fusion energy mission and the UK's wider national AI infrastructure.",
    progress: "Announced in January 2025 that Culham will be the first, and a call for expression of interest to host more was issued the following month. The formal AI Growth Zones application process opened on 30 April. Second AIGZ announced in the North East in September, and North Wales in November",
    lastUpdate: "November"
  },
  {
    id: "R05",
    chapter: "1. Compute & Infrastructure",
    title: "Mitigate the sustainability and security risks of AI infrastructure, while positioning the UK to tak...",
    description: "Mitigate the sustainability and security risks of AI infrastructure, while positioning the UK to take advantage of opportunities to provide solutions.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Spring 2025",
    govResponse: "Agree. DSIT will set out how the UK will seek to address the sustainability and security challenges of AI infrastructure as part of its long-term compute strategy.",
    progress: "AI Energy Council was established in April and met again in June. The Compute Roadmap mentions 'security and sustainability by design' for AIRR.",
    lastUpdate: "July"
  },
  {
    id: "R06",
    chapter: "1. Compute & Infrastructure",
    title: "Agree international compute partnerships with likeminded countries to increase the types of compute ...",
    description: "Agree international compute partnerships with likeminded countries to increase the types of compute capability available to researchers and catalyse research collaborations.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Spring 2025",
    govResponse: "Agree. DSIT will set out its approach to international collaborations as part of its long-term compute strategy.",
    progress: "Expression of Interest opened in spring to host an AI Factory Antenna linked to EuroHPC. EPCC was selected to host it in October. The Compute Roadmap also commits to expanding international partnerships.",
    lastUpdate: "October"
  },
  {
    id: "R07",
    chapter: "2. Data Availability",
    title: "Rapidly identify at least 5 high impact public data sets it National Data Library (NDL) will seek to...",
    description: "Rapidly identify at least 5 high impact public data sets it National Data Library (NDL) will seek to make available to AI researchers and innovators.",
    department: "DSIT",
    status: Status.PARTIALLY,
    deliveryTimeline: "Further details published by Summer 2025",
    govResponse: "Agree. DSIT will explore how it will take forward this recommendation as it develops the National Data Library and its wider data access policy. The government will set out further details on the National Data Library and data access policy in due course.",
    progress: "NDL initiative is in 'scoping phase' with symposia held at KCL in June 2025. The AI for Science Strategy discusses unlocking data in domains like Biobank, which likely represent de facto high-impact sets, but explicit '5 high-impact datasets' list not published.",
    lastUpdate: "November"
  },
  {
    id: "R08",
    chapter: "2. Data Availability",
    title: "(NDL) Strategically shape what data is collected, rather than just making data available that alread...",
    description: "(NDL) Strategically shape what data is collected, rather than just making data available that already exists.",
    department: "DSIT",
    status: Status.PARTIALLY,
    deliveryTimeline: "Further details published by Summer 2025",
    govResponse: "Agree. DSIT will explore how it will take forward this recommendation as it develops the National Data Library and its wider data access policy. The government will set out further details on the National Data Library and data access policy in due course.",
    progress: "Embedded within National Data Library design phase. Blueprint for Modern Digital Government emphasizes federated model with standardized access protocols.",
    lastUpdate: "November"
  },
  {
    id: "R09",
    chapter: "2. Data Availability",
    title: "(NDL) Develop and publish guidelines and best practice for releasing open government data sets which...",
    description: "(NDL) Develop and publish guidelines and best practice for releasing open government data sets which can be used for AI, including on the development of effective data structures and data dissemination methods.",
    department: "DSIT",
    status: Status.DELAYED,
    deliveryTimeline: "Further details published by Summer 2025",
    govResponse: "Agree. DSIT will explore how it will take forward this recommendation as it develops the National Data Library and its wider data access policy. The government will set out further details on the National Data Library and data access policy in due course.",
    progress: "Also part of NDL plans. NDL update was expected in summer",
    lastUpdate: "January"
  },
  {
    id: "R10",
    chapter: "2. Data Availability",
    title: "(NDL) Couple compute allocation with access to proprietary data sets.",
    description: "(NDL) Couple compute allocation with access to proprietary data sets.",
    department: "DSIT",
    status: Status.PARTIALLY,
    deliveryTimeline: "Further details published by Summer 2025",
    govResponse: "Agree. DSIT will explore how it will take forward this recommendation as it develops the National Data Library and its wider data access policy. The government will set out further details on the National Data Library and data access policy in due course.",
    progress: "AI Knowledge Hub launched June 2025 with Guidance Section for government standards. Blueprint for Modern Digital Government sets policy for responsibly sharing high value data.",
    lastUpdate: "November"
  },
  {
    id: "R11",
    chapter: "2. Data Availability",
    title: "(NDL) Build public sector data collection infrastructure and finance the creation of new high-value ...",
    description: "(NDL) Build public sector data collection infrastructure and finance the creation of new high-value data sets that meet public sector, academia and startup needs.",
    department: "DSIT",
    status: Status.PARTIALLY,
    deliveryTimeline: "Further details published by Summer 2025",
    govResponse: "Agree. DSIT will explore how it will take forward this recommendation as it develops the National Data Library and its wider data access policy. The government will set out further details on the National Data Library and data access policy in due course.",
    progress: "AI for Science Strategy (Nov 2025) references leveraging National Data Library to unlock private datasets. Sovereign AI Unit has remit to develop national data assets.",
    lastUpdate: "November"
  },
  {
    id: "R12",
    chapter: "2. Data Availability",
    title: "(NDL) Actively incentivise and reward researchers and industry to curate and unlock private data set...",
    description: "(NDL) Actively incentivise and reward researchers and industry to curate and unlock private data sets.",
    department: "DSIT",
    status: Status.DELAYED,
    deliveryTimeline: "Further details published by Summer 2025",
    govResponse: "Agree. DSIT will explore how it will take forward this recommendation as it develops the National Data Library and its wider data access policy. The government will set out further details on the National Data Library and data access policy in due course.",
    progress: "Also part of NDL plans. NDL update was expected in summer",
    lastUpdate: "January"
  },
  {
    id: "R13",
    chapter: "2. Data Availability",
    title: "Establish a copyright cleared British media asset training data set, which can be licenced internati...",
    description: "Establish a copyright cleared British media asset training data set, which can be licenced internationally at scale.",
    department: "DCMS",
    status: Status.PARTIALLY,
    deliveryTimeline: "Spring 2025",
    govResponse: "Partially agree. DCMS and DSIT will engage with partner organisations and industry to consider the potential role of government in taking forward this recommendation.",
    progress: "The Copyright & AI consultation closed in Feb. Cross-sector working groups were launched in the summer.",
    lastUpdate: "July"
  },
  {
    id: "R14",
    chapter: "3. Talent & Skills",
    title: "Accurately assess the size of the skills gap.",
    description: "Accurately assess the size of the skills gap.",
    department: "Skills England",
    status: Status.COMPLETED,
    deliveryTimeline: "Spring 2025",
    govResponse: "Agree. Working closely with DSIT and the Industrial Strategy Council, Skills England will bring businesses, training partners and unions together with national and local government to develop a clear assessment of the country's skills need – including AI and digital skills – and map pathways by which they can be filled. Updated assessments will be published regularly.",
    progress: "Skills England's AI skills for the UK workforce report was published in October.",
    lastUpdate: "October"
  },
  {
    id: "R15",
    chapter: "3. Talent & Skills",
    title: "Support Higher Education Institutions (HEI) to increase the numbers of AI graduates and teach indust...",
    description: "Support Higher Education Institutions (HEI) to increase the numbers of AI graduates and teach industry-relevant skills.",
    department: "DfE",
    status: Status.COMPLETED,
    deliveryTimeline: "Autumn 2027",
    govResponse: "Agree. DSIT and DfE will work closely with the Office for Students (OfS) and other stakeholders to support HEIs to develop appropriate training, such as AI related degree provision.",
    progress: "Spärck AI Scholarships launched June 2025 (£17.2m) funding Master's degrees at 9 universities (Oxford, Cambridge, Imperial, etc.) to increase AI graduates. UKRI also opened Turing AI Pioneer Interdisciplinary Fellowships call (July).",
    lastUpdate: "July"
  },
  {
    id: "R16",
    chapter: "3. Talent & Skills",
    title: "Increase the diversity of the talent pool.",
    description: "Increase the diversity of the talent pool.",
    department: "DfE",
    status: Status.ON_TRACK,
    deliveryTimeline: "Autumn 2026",
    govResponse: "Agree. DSIT, supported by the DfE, will explore how to scale up and combine where possible, extra-curricular activities for girls in schools to cover AI, building on the National Cyber Security Centre's successful work on cyber security skills. DfE and DSIT will work together with industry to publish a plan to facilitate significant and sustained progress on improving the gender balance across digital education, training and employment.",
    progress: "National Skills Drive (June 2025) includes focus on upskilling existing workforce. Nvidia MoU includes provisions for upskilling and reskilling UK workforce.",
    lastUpdate: "June"
  },
  {
    id: "R17",
    chapter: "3. Talent & Skills",
    title: "Expand education pathways into AI.",
    description: "Expand education pathways into AI.",
    department: "Skills England",
    status: Status.COMPLETED,
    deliveryTimeline: "Autumn 2026",
    govResponse: "Agree. Working closely with the Industrial Strategy Council, Skills England will bring businesses, training partners and unions together with national and local government to meet industry workforce digital and AI skills needs, as set out in the Industrial Strategy.",
    progress: "Skills England published AI skills tools and report in October (AI Skills Framework, Adoption Pathway, Employer Checklist) to widen routes into AI across sectors, complemented by TechFirst strands (Youth, Graduate, Expert, Local).",
    lastUpdate: "October"
  },
  {
    id: "R18",
    chapter: "3. Talent & Skills",
    title: "Launch a flagship undergraduate and master's AI scholarship programme on the scale of Rhodes, Marsha...",
    description: "Launch a flagship undergraduate and master's AI scholarship programme on the scale of Rhodes, Marshall or Fulbright for students to study in the UK.",
    department: "DSIT",
    status: Status.PARTIALLY,
    deliveryTimeline: "Autumn 2026",
    govResponse: "Agree. DSIT will work with UKRI to explore whether the AI scholarships are best placed at undergraduate, master's or PhD level with the aim to establish a new, prestigious scheme by autumn 2026.",
    progress: "Spärck AI Scholarships announced in June, which are fully funded master's degree scholarships at nine universities, with £17.2m backing 'at least 100' master's students. Undergraduate scholarship haven't been announced.",
    lastUpdate: "June"
  },
  {
    id: "R19",
    chapter: "3. Talent & Skills",
    title: "Ensure its lifelong skills programme is ready for AI.",
    description: "Ensure its lifelong skills programme is ready for AI.",
    department: "Skills England",
    status: Status.COMPLETED,
    deliveryTimeline: "Autumn 2025",
    govResponse: "Agree. DFE will take this forward with Skills England, aligning with the work of the independent Curriculum and Assessment Review (CAR) which will report in Autumn 2025. DSIT will engage with the CAR to highlight the importance of digital and AI skills in the curriculum.",
    progress: "Skills England published 'AI skills for the UK workforce' in October, with an AI Skills Framework, Adoption Pathway and Employer Checklist to steer lifelong upskilling. Curriculum & Assessment Review interim report was published in March, with the final report due Autumn 2025. See https://www.gov.uk/government/publications/ai-skills-for-the-uk-workforce",
    lastUpdate: "December"
  },
  {
    id: "R20",
    chapter: "3. Talent & Skills",
    title: "Establish an internal headhunting capability on a par with top AI firms to bring a small number of t...",
    description: "Establish an internal headhunting capability on a par with top AI firms to bring a small number of truly elite individuals to the UK.",
    department: "DBT",
    status: Status.COMPLETED,
    deliveryTimeline: "Spring 2026",
    govResponse: "Agree. DSIT and Department for Business and Trade (DBT) will consider how this could be achieved learning lessons from DBT's existing Global Entrepreneur and Global Talent Network programmes.",
    progress: "Global Talent Taskforce was launched in June to headhunt world-class researchers and innovators to the UK, alongside a £54m Global Talent Fund via 12 delivery institutions.",
    lastUpdate: "June"
  },
  {
    id: "R21",
    chapter: "3. Talent & Skills",
    title: "Explore how the existing immigration system can be used to attract graduates from universities produ...",
    description: "Explore how the existing immigration system can be used to attract graduates from universities producing some of the world's top AI talent.",
    department: "DSIT",
    status: Status.PARTIALLY,
    deliveryTimeline: "Summer 2025",
    govResponse: "Partially agree. The Industrial Strategy will set out how the UK will attract highly skilled AI workers from abroad. The UK offers internationally competitive visas that can support a range of individual needs, including for talent to join UK-based organisations or to start their own business.",
    progress: "The Immigration White Paper introduced immigration changes that affect graduates generally, not AI-specific provisions. The High Potential Individual visa route was expanded (the list of eligible universities is doubled) from 4 Nov 2025, with a cap of 8,000 applications per year.",
    lastUpdate: "October"
  },
  {
    id: "R22",
    chapter: "3. Talent & Skills",
    title: "Expand the Turing AI Fellowships offer.",
    description: "Expand the Turing AI Fellowships offer.",
    department: "DSIT",
    status: Status.COMPLETED,
    deliveryTimeline: "Autumn 2026",
    govResponse: "Agree. DSIT will work with UKRI to expand its AI Fellowship programmes by 2026/2027.",
    progress: "UKRI launched Turing AI Pioneer Interdisciplinary Fellowships in July.",
    lastUpdate: "July"
  },
  {
    id: "R23",
    chapter: "4. Safety & Regulation",
    title: "Continue to support and grow the AI Safety Institute (AISI) to maintain and expand its research on m...",
    description: "Continue to support and grow the AI Safety Institute (AISI) to maintain and expand its research on model evaluations, foundational safety and societal resilience research.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Spring 2025",
    govResponse: "Agree. DSIT will confirm AISI's funding through upcoming Spending Reviews. DSIT will consult on proposed legislation to provide regulatory certainty to help kickstart growth and protect UK citizens and assets from the critical risks associated with the next generation of the most powerful AI models. The government intends to establish AISI as a statutory body.",
    progress: "Ongoing funding through SR25/DSIT R&D allocations.",
    lastUpdate: "October"
  },
  {
    id: "R24",
    chapter: "4. Safety & Regulation",
    title: "Reform the UK text and data mining regime so that it is at least as competitive as the EU.",
    description: "Reform the UK text and data mining regime so that it is at least as competitive as the EU.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "End of 2024",
    govResponse: "The government has launched a consultation.",
    progress: "The Copyright & AI consultation closed in Feb. Cross-sector working groups were launched in the summer.",
    lastUpdate: "July"
  },
  {
    id: "R25",
    chapter: "4. Safety & Regulation",
    title: "Commit to funding regulators to scale up their AI capabilities, some of which need urgent addressing...",
    description: "Commit to funding regulators to scale up their AI capabilities, some of which need urgent addressing.",
    department: "HMT",
    status: Status.PARTIALLY,
    deliveryTimeline: "Spring 2025",
    govResponse: "Agree. Ahead of the Spending Review 2025, each sponsor department will liaise with their regulator to identify the future capability needs for their regulators, taking into account existing funding models, and how they intend to mitigate AI risks and drive growth, which DSIT, with HMT support, will assess.",
    progress: "RIO's October 2025 report references 'AI Capability Fund' but funding is project-based (£8.9m RPF Round 4, £800k DRCF, £260k ONR) rather than systemic uplift. Mechanism exists but scale of funding relative to 'urgent addressing' not fully confirmed.",
    lastUpdate: "October"
  },
  {
    id: "R26",
    chapter: "4. Safety & Regulation",
    title: "Ensure all sponsor departments include a focus on enabling safe AI innovation in their strategic gui...",
    description: "Ensure all sponsor departments include a focus on enabling safe AI innovation in their strategic guidance to regulators.",
    department: "DBT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Initially Spring 2025, but continuous thereafter",
    govResponse: "Agree. Relevant sponsor departments commit to stressing the importance of safe AI innovation in their strategic guidance to regulators – where this is identified as an issue, and where legislation requires/allows for such guidance to be issued.",
    progress: "RIO's One Year On report shows delivery via: £3.6m AI Capability Fund awards (e.g. DRCF's digital regulatory library, ICO testing AI data-protection technologies, Ofgem building an AI tool to accelerate up to £30bn infrastructure funding, ONR running an AI sandbox for nuclear). In addition, ~£8.9m RPF Round 4 to 16 regulator/local-authority projects and scaling the MHRA AI Airlock.",
    lastUpdate: "October"
  },
  {
    id: "R27",
    chapter: "4. Safety & Regulation",
    title: "Work with regulators to accelerate AI in priority sectors and implement pro-innovation initiatives l...",
    description: "Work with regulators to accelerate AI in priority sectors and implement pro-innovation initiatives like regulatory sandboxes.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Initially Spring 2025, but continuous thereafter",
    govResponse: "Agree. DSIT, through the RIO, will identify priority sectors with high-growth potential and work with relevant regulators to identify pro-innovation initiatives. DSIT will update on progress by Summer 2025.",
    progress: "DSIT opened a call for evidence on an economy-wide AI Growth Lab (a sandbox). Sector-specific activity continues in the meantime (e.g. ONR project using AI sandbox for nuclear).",
    lastUpdate: "October"
  },
  {
    id: "R28",
    chapter: "4. Safety & Regulation",
    title: "Require all regulators to publish annually how they have enabled AI innovation in their sector.",
    description: "Require all regulators to publish annually how they have enabled AI innovation in their sector.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Initially Spring 2025, but continuous thereafter",
    govResponse: "Agree. Sponsor departments will request that regulators with significant AI activities publicly report on their activities to promote AI innovation. Where this is not already happening, DSIT will work with sponsor departments to request this and will provide an update on progress as part of a wider update on regulators with significant AI activity by Summer 2025.",
    progress: "Government introduced a 'public dashboard to allow businesses to review the performance of regulators' alongside strengthened Growth Duty in late 2025. This dashboard mechanism serves the same transparency function as annual reporting.",
    lastUpdate: "November"
  },
  {
    id: "R29",
    chapter: "4. Safety & Regulation",
    title: "Support the AI assurance ecosystem to increase trust and adoption by investing in new assurance tool...",
    description: "Support the AI assurance ecosystem to increase trust and adoption by: a) Investing significantly in the development of new assurance tools, including through an expansion to AISI's systemic AI safety fast grants programme to support emerging safety research and methods. b) Building government-backed high-quality assurance tools that assess whether AI systems perform as claimed and work as intended.",
    department: "DSIT",
    status: Status.COMPLETED,
    deliveryTimeline: "Spring 2026",
    govResponse: "Agree. DSIT will seek to prioritise additional funding for AISI's Systemic AI safety programme at Spending Reviews, as well as support DSIT's existing programme of work designed to stimulate the AI Assurance ecosystem. DSIT will also explore other options for growing the domestic AI safety market and provide a public update on this by Spring 2025.",
    progress: "Trusted Third-Party AI Assurance Roadmap was launched in September, an £11m AI Assurance Innovation Fund was announced. AISI's Systemic AI Safety grants are running, with first 20 projects selected.",
    lastUpdate: "September"
  },
  {
    id: "R30",
    chapter: "4. Safety & Regulation",
    title: "Consider the broader institutional landscape and the potential of the Alan Turing Institute to drive...",
    description: "Consider the broader institutional landscape and the potential of the Alan Turing Institute to drive progress at the cutting edge, support the government's missions and attract international talent.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Update in Autumn 2025",
    govResponse: "Agree. DSIT will work with the Alan Turing Institute and UKRI to drive progress at the cutting edge, support the government's missions and attract international talent.",
    progress: "Government pressed ATI to pivot toward national priorities, especially national security in July. Some projects have since been reoriented or closed and some leadership changes have been made to support the reset. ATI has also announced a new Science and Innovation Programme focused on defence/national security, environment & sustainability, and health, including a mission to protect critical national infrastructure from cyber attacks. Independent review by Blythe Crawford has been announced.",
    lastUpdate: "October"
  },
  {
    id: "R31",
    chapter: "5. Public Sector Adoption",
    title: "SCAN - appoint an AI lead for each mission to help identify where AI could be a solution within the ...",
    description: "SCAN - appoint an AI lead for each mission to help identify where AI could be a solution within the mission setting, considering the user needs from the outset.",
    department: "DSIT",
    status: Status.PARTIALLY,
    deliveryTimeline: "Update Autumn 2025. Ongoing thereafter.",
    govResponse: "Agree. In its role as Digital Centre for Government, DSIT will appoint an AI lead for each mission to help identify where AI could be a solution.",
    progress: "Blueprint for Modern Digital Government consolidated digital leadership into Digital Centre for Government. AI leadership function has been centralized to work with mission leads, though distinct 'Mission AI Lead' individuals not prominently featured in press releases.",
    lastUpdate: "November"
  },
  {
    id: "R32",
    chapter: "5. Public Sector Adoption",
    title: "SCAN - a cross-government, technical horizon scanning and market intelligence capability that unders...",
    description: "SCAN - a cross-government, technical horizon scanning and market intelligence capability that understands AI capabilities and use-cases as they evolve to work closely with mission leads and maximise the expertise of both.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Update in Autumn 2025",
    govResponse: "Agree. DSIT will build a cross-government technical horizon scanning and market intelligence capability that understands AI capabilities. Linked to this, the government will consider how it can support adoption in the private sector, for example sharing emergent use-cases and enabling diffusion across sectors.",
    progress: "Delivery is through DSIT and the AI Exemplars 'scan-pilot-scale' portfolio, which is scanning opportunities across departments.",
    lastUpdate: "August"
  },
  {
    id: "R33",
    chapter: "5. Public Sector Adoption",
    title: "SCAN - 2-way partnerships with AI vendors and startups to anticipate future AI developments and sign...",
    description: "SCAN - 2-way partnerships with AI vendors and startups to anticipate future AI developments and signal public sector demand.",
    department: "DSIT",
    status: Status.COMPLETED,
    deliveryTimeline: "Update in Summer 2025",
    govResponse: "Agree. DSIT will explore 2-way partnerships with AI vendors and startups to anticipate future AI developments and signal public sector demand.",
    progress: "High-profile MoUs signed in 2025 with Anthropic (Feb), Nvidia (June), Cohere (June), and OpenAI (July). Partnerships explicitly designed to 'anticipate future AI developments' and 'upskill the UK workforce'. AI Exemplars also involve multi-department supplier projects.",
    lastUpdate: "August"
  },
  {
    id: "R34",
    chapter: "5. Public Sector Adoption",
    title: "PILOT - consistent use of a framework for how to source AI - whether to build in-house, buy or run i...",
    description: "PILOT - consistent use of a framework for how to source AI - whether to build in-house, buy or run innovation challenges - that evolves over time, given data, capability, industry contexts and evaluation of what's worked.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Summer 2025",
    govResponse: "Agree. DSIT will develop a framework for sourcing AI – whether to build in-house, buy or run innovation challenges.",
    progress: "Blueprint for Modern Digital Government outlines strategy for 'Fund for outcomes, procure for growth' with procurement consistency guidance. AI Knowledge Hub provides guidance on 'how to introduce AI safely' including sourcing decisions.",
    lastUpdate: "November"
  },
  {
    id: "R35",
    chapter: "5. Public Sector Adoption",
    title: "PILOT - a rapid prototyping capability that can be drawn on for key projects where needed, including...",
    description: "PILOT - a rapid prototyping capability that can be drawn on for key projects where needed, including technical and delivery resource to build and test proof of concepts, leveraging in house AI expertise, together with specialists in design and user experience.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "At Digital Centre launch",
    govResponse: "Agree. DSIT will have a rapid prototyping capability as part of the new Digital Centre of Government in DSIT.",
    progress: "AI Exemplars/i.AI resources mention 'building 22 AI prototypes with 11 now at Alpha or Beta stage, all within the last 12 months'.",
    lastUpdate: "August"
  },
  {
    id: "R36",
    chapter: "5. Public Sector Adoption",
    title: "PILOT - specific support to hire external AI talent.",
    description: "PILOT - specific support to hire external AI talent.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Ongoing, update in Autumn 2025",
    govResponse: "Agree. DSIT will build on i.AI and GDS's work to hire external AI talent.",
    progress: "Central support will be strengthened via Responsible AI Advisory Panel (recruitment took place in July), and the Open-Source AI Fellowship bringing top engineers into government.",
    lastUpdate: "July"
  },
  {
    id: "R37",
    chapter: "5. Public Sector Adoption",
    title: "PILOT - a data-rich experimentation environment including streamlined approach to accessing data set...",
    description: "PILOT - a data-rich experimentation environment including streamlined approach to accessing data sets, access to language models and necessary infrastructure like compute.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Update in Autumn 2025",
    govResponse: "Agree. DSIT will build on i.AI's experimentation environment including streamlined approaches to accessing data sets, access to language models and necessary infrastructure like compute.",
    progress: "Incubator for AI's AI Knowledge Hub launched to share guidance, case studies and tools. The AI Growth Lab call (a cross-economy sandbox) aims to complement experimentation.",
    lastUpdate: "October"
  },
  {
    id: "R38",
    chapter: "5. Public Sector Adoption",
    title: "PILOT - a faster, multi-stage gated and scaling AI procurement process that enables easy and quick a...",
    description: "PILOT - a faster, multi-stage gated and scaling AI procurement process that enables easy and quick access to small-scale funding for pilots and only layers bureaucratic controls as the investment-size gets larger.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Update in Autumn 2025",
    govResponse: "Agree. DSIT will scope and understand options to improve AI procurement with a faster, multi-stage, gated process.",
    progress: "Blueprint for Modern Digital Government prioritizes strengthening digital and data public infrastructure. National Data Library and Compute Roadmap investment provide backbone.",
    lastUpdate: "November"
  },
  {
    id: "R39",
    chapter: "5. Public Sector Adoption",
    title: "SCALE - a scaling service for successful pilots with senior support and central funding resource.",
    description: "SCALE - a scaling service for successful pilots with senior support and central funding resource.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Update in Autumn 2025",
    govResponse: "Agree DSIT will scope the development of a scaling service that takes successful pilots and drives wide implementation.",
    progress: "Scaling support is being operationalised through the AI Exemplars portfolio, which is designed for the scan-pilot-scale process across departments.",
    lastUpdate: "August"
  },
  {
    id: "R40",
    chapter: "5. Public Sector Adoption",
    title: "SCALE - mission-focused national AI tenders to support rapid adoption across decentralised systems l...",
    description: "SCALE - mission-focused national AI tenders to support rapid adoption across decentralised systems led by the mission delivery boards.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Update in Autumn 2025",
    govResponse: "Agree. DSIT will scope options to improve AI procurement with mission-focused national AI tenders.",
    progress: "DSIT ran pre-market engagement in March and then issued a Find-a-Tender notice in August for a national AI tender to build a GOV.UK agentic AI companion. In October, DSIT published a tender to help it develop an 'AI-augmented decision-making tool' to speed up planning applications. No public list yet of additional national AI tenders.",
    lastUpdate: "October"
  },
  {
    id: "R41",
    chapter: "5. Public Sector Adoption",
    title: "SCALE - development or procurement of a scalable AI tech stack that supports the use of specialist n...",
    description: "SCALE - development or procurement of a scalable AI tech stack that supports the use of specialist narrow and large language models for tens or hundreds of millions of citizen interactions across the UK.",
    department: "DSIT",
    status: Status.NOT_STARTED,
    deliveryTimeline: "Update in Autumn 2025",
    govResponse: "Agree DSIT will learn from other countries, such as Singapore's GovTech, to explore options for building on GDS and i.AI's tech stack.",
    progress: "DSIT to engage with other countries on options for building on GDS and i.AI's tech stack for scalable AI.",
    lastUpdate: "January"
  },
  {
    id: "R42",
    chapter: "5. Public Sector Adoption",
    title: "SCALE - mandating infrastructure interoperability, code reusability and open sourcing.",
    description: "SCALE - mandating infrastructure interoperability, code reusability and open sourcing.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Update in Autumn 2025",
    govResponse: "Agree. DSIT will commit to interoperable, reusable, and open source code whenever appropriate, in line with the Technology Code of Practice.",
    progress: "DSIT has committed to using open source code where possible in line with the Technology Code of Practice. Some departments (e.g. DWP) have refreshed open source publishing policy.",
    lastUpdate: "October"
  },
  {
    id: "R43",
    chapter: "5. Public Sector Adoption",
    title: "Procure smartly from the AI ecosystem as both its largest customer and as a market shaper.",
    description: "Procure smartly from the AI ecosystem as both its largest customer and as a market shaper.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Update in Autumn 2025",
    govResponse: "Agree. DSIT will procure smartly from the AI ecosystem.",
    progress: "Guidance is published in the AI Playbook. Delivery is through the AI Exemplars programme working with suppliers across departments.",
    lastUpdate: "August"
  },
  {
    id: "R44",
    chapter: "5. Public Sector Adoption",
    title: "Use digital government infrastructure to create new opportunities for innovators.",
    description: "Use digital government infrastructure to create new opportunities for innovators.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Update in Autumn 2025",
    govResponse: "Agree. DSIT will scope options to use digital government infrastructure to create new opportunities for innovators, including through scoping improvements to AI procurement with a faster, multi-stage, gated process and through Mission-focused national AI tenders.",
    progress: "Government set out further detail in the 'Blueprint for modern digital government'.",
    lastUpdate: "January"
  },
  {
    id: "R45",
    chapter: "5. Public Sector Adoption",
    title: "Publish best-practice guidance, results, case-studies and open-source solutions through a single, 'AI Knowledge Hub'.",
    description: "Publish best-practice guidance, results, case-studies and open-source solutions through a single, 'AI Knowledge Hub'.",
    department: "DSIT",
    status: Status.COMPLETED,
    deliveryTimeline: "Summer 2025",
    govResponse: "Agree. DSIT will pilot the AI Knowledge Hub.",
    progress: "AI Knowledge Hub is live and includes guidance, tools and case studies for public sector teams, with the content growing regularly.",
    lastUpdate: "Rolling"
  },
  {
    id: "R46",
    chapter: "5. Public Sector Adoption",
    title: "In the next 3 months, the Digital Centre of Government should identify a series of quick wins to sup...",
    description: "In the next 3 months, the Digital Centre of Government should identify a series of quick wins to support the adoption of the scan, pilot scale approach and enable public and private sector to reinforce each other.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Summer 2025",
    govResponse: "Agree. DSIT has identified the following 'quick wins', and will rapidly work to: 1. Scale and open source 1-2 public sector-led AI solutions that are currently in pilot phase. 2. Scale a citizen facing AI tool that enables citizens to engage with government in a more personalised and efficient way. 3. Run Hackathons, aligned to the five key missions. 4. Pilot the AI Knowledge Hub. 5. Appoint an AI lead for each mission to help identify where AI could be a solution.",
    progress: "i.AI delivering quick wins: Redbox (document summarization), Consult (consultation analysis), Extract (planning data). RIO announced 16 projects to cut red tape (Oct 2025).",
    lastUpdate: "October"
  },
  {
    id: "R47",
    chapter: "5. Public Sector Adoption",
    title: "Leverage the new Industrial Strategy. The development of a new Industrial Strategy presents an oppor...",
    description: "Leverage the new Industrial Strategy. The development of a new Industrial Strategy presents an opportunity to drive collective action to support AI adoption across the economy.",
    department: "DBT",
    status: Status.COMPLETED,
    deliveryTimeline: "Spring 2025",
    govResponse: "Agree. DSIT will work with HMT, DBT and lead departments, as part of the Industrial Strategy development, to identify opportunities for AI adoption in key industries. This work will build on the Cross-government Review of Technology Adoption for Growth, Innovation and Productivity led by Government Chief Scientific Adviser (GCSA), Professor Dame Angela McLean with National Technology Adviser (NTA) Dr Dave Smith.",
    progress: "Industrial Strategy and sector plans (e.g. Digital & Technologies, Life Sciences, PBS) embed AI adoption throughout.",
    lastUpdate: "June"
  },
  {
    id: "R48",
    chapter: "5. Public Sector Adoption",
    title: "Appoint AI Sector Champions in key industries like the life sciences, financial services and the cre...",
    description: "Appoint AI Sector Champions in key industries like the life sciences, financial services and the creative industries to work with industry and government and develop AI adoption plans.",
    department: "DBT",
    status: Status.COMPLETED,
    deliveryTimeline: "Summer 2025",
    govResponse: "Agree. DSIT, HMT and DBT will work via the Industrial Strategy to identify where industry leaders with AI-specific sector expertise have a role to play in driving adoption, informed by knowledge of the current market for solutions and needs of each sector.",
    progress: "AI Sector Champions appointed November 2025: Shaheen Sayed (Professional Business Services), Chris Dungey (Advanced Manufacturing), Lucy Yu (Clean Energy). Tom Blomfield appointed as AI ambassador for SMEs.",
    lastUpdate: "November"
  },
  {
    id: "R49",
    chapter: "5. Public Sector Adoption",
    title: "Drive AI adoption across the whole country.",
    description: "Drive AI adoption across the whole country.",
    department: "DSIT",
    status: Status.ON_TRACK,
    deliveryTimeline: "Initially Summer 2025, then continuous",
    govResponse: "Agree. DSIT will work with devolved and local government to identify AI adoption development opportunities to drive growth and, where an opportunity is identified, to incorporate AI adoption objectives into Local Growth Plans within the next twelve months.",
    progress: "AI Growth Zones designated in North East England, North Wales, and South Wales. Zones tied to Local Growth Plans with funding for local skills and infrastructure.",
    lastUpdate: "November"
  },
  {
    id: "R50",
    chapter: "6. Sovereign AI",
    title: "Create a new unit, with the power to partner with the private sector to deliver the clear mandate of...",
    description: "Create a new unit, with the power to partner with the private sector to deliver the clear mandate of maximising the UK's stake in frontier AI.",
    department: "DSIT",
    status: Status.COMPLETED,
    deliveryTimeline: "Further details to be shared by Spring 2025",
    govResponse: "Agree. The government will create a new function which will draw on wider government functions to partner with AI companies, including by: Leveraging AI Growth Zones to support partnered companies; Exploring making available high-potential data sets for partnered companies; Supporting top AI talent to relocate to the UK; Helping to build relationships between partnered AI companies and the UK's national security community.",
    progress: "The unit is operating. Early delivery includes: Compute access call for short-term AIRR projects in June, Sovereign AI 'Series One' Proof-of-Concept competition in August-September, OpenBind (£8m seed to DLS/Oxford-led consortium to build the world's largest open protein-ligand dataset), and Encode: AI for Science fellowship expansion. In addition, through the unit several MoUs with companies, such as NVIDIA, OpenAI and Cohere, have been signed, alongside a more formal partnership with Anthropic.",
    lastUpdate: "August"
  },
];
