export interface EvidenceSource {
  id: number;
  title: string;
  url: string;
}

export const EVIDENCE_SOURCES: EvidenceSource[] = [
  { id: 1, title: "UK Compute Roadmap - Parliament", url: "https://questions-statements.parliament.uk/written-statements/detail/2025-07-21/hlws859" },
  { id: 2, title: "UK Compute Roadmap - GOV.UK", url: "https://www.gov.uk/government/publications/uk-compute-roadmap" },
  { id: 3, title: "AI Growth Zones", url: "https://www.gov.uk/government/collections/ai-growth-zones" },
  { id: 4, title: "DSIT - Sparck AI Scholarships", url: "https://www.gov.uk/government/news/top-talent-backed-with-masters-funding-as-britains-tech-experts-called-into-government" },
  { id: 5, title: "Lords Library - Copyright and AI", url: "https://lordslibrary.parliament.uk/copyright-and-artificial-intelligence-impact-on-creative-industries/" },
  { id: 6, title: "Hogan Lovells - High Court AI ruling", url: "https://www.hoganlovells.com/en/publications/getty-loses-uk-copyright-case-against-stability-ai-" },
  { id: 7, title: "UK Compute Roadmap (HTML)", url: "https://www.gov.uk/government/publications/uk-compute-roadmap/uk-compute-roadmap" },
  { id: 8, title: "UKRI - Isambard-AI Bristol", url: "https://www.ukri.org/news/bristol-scientists-and-innovators-are-making-our-lives-better/" },
  { id: 10, title: "UKRI - AIRR AI for Science", url: "https://www.ukri.org/opportunity/airr-compute-opportunity-ai-for-science/" },
  { id: 11, title: "Sovereign AI Unit", url: "https://www.gov.uk/government/collections/sovereign-ai-unit" },
  { id: 12, title: "Delivering AI Growth Zones", url: "https://www.gov.uk/government/publications/delivering-ai-growth-zones/delivering-ai-growth-zones" },
  { id: 13, title: "CMS LawNow - Power Update", url: "https://cms-lawnow.com/en/ealerts/2025/11/once-shaken-now-stirred-winter-2025-power-update-for-data-centres-and-other-large-energy-users" },
  { id: 14, title: "Data Centre Review - North Wales AIGZ", url: "https://datacentrereview.com/2025/11/new-north-wales-ai-growth-zone-promises-to-create-3400-jobs/" },
  { id: 15, title: "Digit.fyi - AI Energy Council", url: "https://www.digit.fyi/ai-council-looks-to-energy-grid-reform-to-power-growth-zones/" },
  { id: 16, title: "BCLP Law - AI Action Plan", url: "https://www.bclplaw.com/en-US/events-insights-news/govt-ai-action-plan.html" },
  { id: 17, title: "Government Response PDF", url: "https://assets.publishing.service.gov.uk/media/678639913a9388161c5d2376/ai_opportunities_action_plan_government_repsonse.pdf" },
  { id: 18, title: "Technology Adoption Review", url: "https://assets.publishing.service.gov.uk/media/6857e0995225e4ed0bf3ceb5/dsit_technology_adoption_review_web.pdf" },
  { id: 19, title: "KCL - National Data Library", url: "https://www.kcl.ac.uk/developing-the-uk-national-data-library-for-public-benefit-10-key-reflections" },
  { id: 21, title: "Blueprint for Digital Government", url: "https://www.gov.uk/government/publications/a-blueprint-for-modern-digital-government/a-blueprint-for-modern-digital-government-html" },
  { id: 22, title: "UKRI Corporate Plan", url: "https://www.ukri.org/publications/uk-research-and-innovation-corporate-plan-update-2025-to-2027/ukri-corporate-plan-update-2025-to-2027/" },
  { id: 23, title: "AI for Science Strategy", url: "https://www.gov.uk/government/publications/ai-for-science-strategy" },
  { id: 24, title: "AI Knowledge Hub - Burges Salmon", url: "https://www.burges-salmon.com/articles/102kfnd/public-sector-and-ai-uk-government-ai-knowledge-hub-published/" },
  { id: 25, title: "AI Knowledge Hub Blog", url: "https://ai.gov.uk/blogs/introducing-the-ai-knowledge-hub-sharing-lessons-about-public-sector-ai" },
  { id: 26, title: "Oxford Insights", url: "https://oxfordinsights.com/insights/tracking-progress-on-the-uks-ai-opportunities-action-plan-implementation-is-what-counts-for-growth/" },
  { id: 27, title: "Oxford Academic - Copyright", url: "https://academic.oup.com/grurint/article/74/11/1055/8209765" },
  { id: 28, title: "PM National Skills Drive", url: "https://www.gov.uk/government/news/pm-launches-national-skills-drive-to-unlock-opportunities-for-young-people-in-tech" },
  { id: 29, title: "APC AI Skills Gap Report", url: "https://www.apcuk.co.uk/wp-content/uploads/2025/10/AI-Skills-Gap-Report.pdf" },
  { id: 30, title: "UCL AI Scholars", url: "https://www.ucl.ac.uk/news/2025/jun/ucl-host-ai-scholars-part-uk-governments-tech-talent-programme" },
  { id: 31, title: "Southampton AI Scholarship", url: "https://www.southampton.ac.uk/news/2025/06/southampton-to-lead-new-ai-scholarship.page" },
  { id: 32, title: "UKRI Turing Fellowships", url: "https://www.ukri.org/opportunity/turing-ai-world-leading-researcher-fellowships-round-three/" },
  { id: 33, title: "DSIT R&D Investment", url: "https://www.gov.uk/government/news/more-targeted-rd-investment-towards-driving-uk-growth-and-jobs-unveiled-by-technology-secretary" },
  { id: 34, title: "Newcastle - Sparck AI", url: "https://www.ncl.ac.uk/press/articles/latest/2025/06/sparckaischolarships/" },
  { id: 35, title: "RIO One Year On", url: "https://www.gov.uk/government/publications/regulatory-innovation-office-report-one-year-on/regulatory-innovation-office-one-year-on-html" },
  { id: 36, title: "Re-State Review", url: "https://re-state.co.uk/review/review-24-october-2025/" },
  { id: 37, title: "White & Case AI Watch", url: "https://www.whitecase.com/insight-our-thinking/ai-watch-global-regulatory-tracker-united-kingdom" },
  { id: 38, title: "Parallel Parliament Lords", url: "https://www.parallelparliament.co.uk/live/2025-07-21/lords-chamber" },
  { id: 39, title: "techUK Digital Centre", url: "https://www.techuk.org/resource/digital-centre-for-government-sets-out-a-blueprint-for-modern-digital-government.html" },
  { id: 40, title: "Incubator for AI", url: "https://ai.gov.uk/" },
  { id: 41, title: "Gov cuts red tape", url: "https://www.gov.uk/government/news/government-cuts-red-tape-to-revolutionise-public-services-with-cutting-edge-tech" },
  { id: 42, title: "GDS About", url: "https://www.gov.uk/government/organisations/government-digital-service/about" },
  { id: 43, title: "Open Loop - CMA AI Principles", url: "https://openloop.org/reports/2025/02/competition-in-ai-foundation-models-and-the-cma-ai-principles.pdf" },
  { id: 44, title: "Parliament AI Governance", url: "https://publications.parliament.uk/pa/cm5901/cmselect/cmsctech/591/report.html" },
  { id: 45, title: "King & Spalding EU/UK AI", url: "https://www.kslaw.com/news-and-insights/eu-uk-ai-round-up-july-2025" },
  { id: 46, title: "Gov AI Investment Announcement", url: "https://www.gov.uk/government/news/ai-to-power-national-renewal-as-government-announces-billions-of-additional-investment-and-new-plans-to-boost-uk-businesses-jobs-and-innovation" },
  { id: 47, title: "Budget - Tech Firms", url: "https://www.gov.uk/government/news/budget-backs-technology-firms-to-start-up-scale-up-and-stay-in-britain-to-drive-growth-and-national-renewal" },
];

// Mapping from Key_sources in the Gemini Report
export const RECOMMENDATION_SOURCES: Record<string, number[]> = {
  R01: [1, 7],
  R02: [1, 8, 10],
  R03: [1, 11],
  R04: [3, 12, 14],
  R05: [15, 16],
  R06: [17, 18],
  R07: [19],
  R08: [21, 22],
  R09: [23],
  R10: [21, 24],
  R11: [11, 23],
  R12: [26],
  R13: [5, 6, 27],
  R14: [28, 29],
  R15: [4, 31],
  R16: [11, 28],
  R17: [11, 17],
  R18: [32],
  R19: [21, 30],
  R20: [4, 33],
  R21: [1, 11],
  R22: [4, 34],
  R23: [11, 28],
  R24: [5, 6],
  R25: [35],
  R26: [35, 36],
  R27: [35, 37],
  R28: [36],
  R30: [33],
  R31: [21, 39],
  R32: [35, 40],
  R33: [11],
  R34: [21, 25],
  R35: [39, 41],
  R36: [24],
  R37: [40],
  R38: [21],
  R39: [39, 42],
  R40: [43],
  R44: [12],
  R46: [46],
  R47: [47],
  R48: [47],
  R49: [3],
  R50: [11],
};

// Helper function to get sources for a recommendation
export function getSourcesForRecommendation(recId: string): EvidenceSource[] {
  const sourceIds = RECOMMENDATION_SOURCES[recId] || [];
  return sourceIds
    .map(id => EVIDENCE_SOURCES.find(s => s.id === id))
    .filter((s): s is EvidenceSource => s !== undefined);
}
